---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Rules for the operator
  ##
  - apiGroups:
      - config.nri
    resources:
      - nriplugindeployments
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - config.nri
    resources:
      - nriplugindeployments/status
    verbs:
      - get
      - update
      - patch
  ##
  ## Rules for config.nri/v1alpha1, Kind: NriPluginDeployment
  ##
  - verbs:
    - "*"
    apiGroups:
    - "rbac.authorization.k8s.io"
    - "apps"
    - ""
    resources:
    - "clusterrolebindings"
    - "clusterroles"
    - "rolebindings"
    - "roles"
    - "daemonsets"
    - "configmaps"
    - "serviceaccounts"
    - "namespaces"
    - "secrets"
 #+kubebuilder:scaffold:rules
